sudo: required
dist: trusty
language: cpp

env:
  global:
    - LANG="en_US.UTF-8"
    - COVERAGE=false

compiler:
  - gcc

# need gcc 4.9 and cmake
os:
  - linux
addons:
  apt:
    sources:
      #- ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      #- g++-4.9
      - cmake-data
      - cmake
      - lcov
  #sonarcloud
  sonarcloud:
    organization: "ark-game"
    token:
        secure: "UKdEfrDHDQvUyGSoGwgXBXgTl1jtPX1mLa7DKxB8YxsQXKlGXwmF5tle2+odyFmb2Ps8dSfO7tjRwpY2r5jYOO3RLNXIFuKI/z2d5MOvjXRck4EUaHm/OXomNZj2WnCjRu7G9rRLpgGCQX0ExKd2cyO13wRltHTrdz5UOv8NBHtA56CaRTi/Nr017cYievQJ6S0fMOsrG+H4zUmHW9Q6sm6zdJ37gnB4oz/VP79qd+k8anOftZJC/vT/rRTN63Hccs5zuOeV1Wn1XAYyHE1EK1P338cx0PGzfL0n71izeVER6hl2S+sGXXXRsuInv1ZCmQLIFHUuM6hcHK1L+6q96ClHQKB2R2Jc7Ctv21WogyyU5e+uAvZUiQrZEkywut6DCVpACzqjrh+LB8DqJvo455Uq12/PJoaII/4hZGrFAOOUDBN/A2Ut0kTRdUGlZ1iFrCrPSXOSXLZGphfFAvJRXeGFuNIad2+4FereuHkMzQmw3sf1EsqQ87lANpfkEYrPL7XKbhmgcjcgKoifsQ469mcTujs076qYtbufl8i7k+iy3NCa/7s+QqAEDu2RBdv/r9OkDxR/CDkuPJxpHgfHIziQpfUoj6Z4vTICuDSrlndhRFKK6Fx8Qu9cGWuh2Excewp4paDUKOGzKVEKXKSvnJwSGkzv0/PW/yI8KkpSrRE="
before_install:
  # run build_dep.sh
  - pwd
  - cd Dep
  - chmod -R 755 build_dep.sh
  - ./build_dep.sh
  - cd ..

install:
    #- sudo pip install --upgrade pip
    #- sudo pip install codecov
  
before_script:
  # cmake
  - if [-d "build" ]; then rm -rf build; fi
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DENABLE_COVERAGE=ON ..

script:
  # make
  - build-wrapper-linux-x86-64 --out-dir bw-output make -j 4
  - echo $TRAVIS_BUILD_DIR/Frame
  - cd $TRAVIS_BUILD_DIR/Frame
  #If you need debug log, plase add -X parameters
  - sonar-scanner
    
after_success:
  #- bash <(curl -s https://codecov.io/bash)
  
cache:
  directories:
    - '$HOME/.sonar/cache'

notifications:
  email:
    - nickyang1988@qq.com
    - 410274624@qq.com
